[tool.ruff]
line-length = 100
target-version = "py313"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.lint]
select = [
    "E",      # Ошибки стиля (pycodestyle)
    "W",      # Предупреждения стиля (pycodestyle)
    "F",      # Ошибки логики (Pyflakes)
    "I",      # Автоматическая сортировка импортов (isort)
    "UP",     # Обновление синтаксиса до новых версий Python
    "B",      # Нахождение вероятных багов (flake8-bugbear)
    "PT",     # Оптимизация тестов Pytest
    "ARG",    # Поиск неиспользуемых аргументов функций
    "D", # Включаем проверку документации (pydocstyle)
    "D213", # Явно приказываем: текст СО ВТОРОЙ строки
]

ignore = [
    "D100", # Нет докстрига в начале файла
    "D101", # Отсутствует строка документации в публичном классе
    "D102", # Отсутствует строка документации в публичном методе
    "D103", # Отсутствует строка документации в публичной функции
    "D105", # Отсутствует строка документации в магическом методе
    "D107", # Отсутствует строка документации в __init__
    "D200", # Не схлопывать документацию в одну строку
    "D203", # "Перед строкой документации класса требуется 1 пустая строка" (выключаем лишнее)
    "D212", # "Многострочная документация должно начинаться с первой строки" (выключаем это)
]
extend-unsafe-fixes = [
    "D201",
    "D205",
    "D209",
    "D213",
    "D300",
    "D415",
    "D400",
    "D416"
]

[tool.ruff.lint.isort]
combine-as-imports = true

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false # Важно: Ruff будет сохранять ваши запятые для переносов
docstring-code-format = true      # Форматирует примеры кода в докстрингах

[tool.poetry]
name = "velvet-v2"
version = "0.1.0"
description = ""
authors = ["boradydev"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.13"
alembic = "^1.18.3"
pydantic-settings = "^2.12.0"
ruff = "^0.14.14"
pyright = "^1.1.408"
sqlalchemy = "^2.0.46"
asyncpg = "^0.31.0"
psycopg2-binary = "^2.9.11"
passlib = "^1.7.4"
pyjwt = "^2.11.0"
fastapi = "^0.128.0"
uvicorn = "^0.40.0"
jinja2 = "^3.1.6"
uuid6 = "^2025.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
